version: "3.8"
services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: gnews
    ports:
      - 27017:27017

  gnews:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
